### ISSUE TITLE
Can't get options to work

### ISSUE THREAD

**Issue by nataliawojtkowska** [redxtech/vue-plyr#11] opened 2018-04-11 13:44 UTC
I specify the config in data like 
```
options: {
     volume: 0
},
```
```
<plyr-video :options="options"  :videos="videos"  :crossorigin="true" />
```

**Comment by jwjcmw** [comment] 2018-04-12 12:55
Have you tried some other options?  I just tried volume, and it doesn't do anything for me either...but other options do work (html, autoplay).  This may be an issue with plyr itself.  Note I just tested this on a 2.x version of plyr...not sure if 3 is any different.

**Comment by smilingpeanut** [comment] 2018-06-06 18:41
@redxtech I'm struggling with this as well. Trying to customize the controls and can't seem to figure it out. How is the prop supposed to be structured?

**Comment by bgantick** [comment] 2018-06-14 14:48
I was able to get this working (with an audio instance specifically). Example:

```
<plyr :options="options">
  <audio>
    <source :src="file" type="audio/mp3" />
  </audio>
</plyr>
```

```
props: {
  file: String,
  options: {
    type: Object,
    default: function () {
      return { selectors: { container: 'test' } }
    }
  }
}
```

**Comment by redxtech** [comment] 2018-07-24 23:46
I have tried with a multitude of different options and I'm unable to reproduce. Closing for now. Feel free to reopen if you have more issues.

Note: I was unable to get volume working properly. This is mostly likely an issue with plyr itself. Feel free to make an issue there.

**Closed by redxtech** 2018-07-24 23:46 UTC
