### ISSUE TITLE
Microsoft Edge issue: [vue-router] Failed to resolve async component default: SyntaxError: Expected identifier, string or number

### ISSUE THREAD

**Issue by vahost** [redxtech/vue-plyr#190] opened 2020-05-30 12:42 UTC
My new app runs without errors in Chrome and other browsers, but it generates an error in Microsoft Edge's (pre-Chromium) console, and the app returns a blank page.

> [vue-router] Failed to resolve async component default: SyntaxError: Expected identifier, string or number
> eval code (1557) (17,5)
> 
> [vue-router] uncaught error during route navigation:
> eval code (1557) (17,5)
> 
> [object Error]: {description: “Expected identifier, string or number”, message: “Expected identifier, string or number”, number: -2146827260, stack: “SyntaxError: Expected identifier, string or number at ./node_modules/vue-plyr/dist/vue-plyr.mjs (http://localhost:8080/vendor.js:2878:1) at webpack_require (http://localhost:8080/app.js:854:12) at fn (http://localhost:8080/app.js:151:13) at eval code (eval code:3:22) at ./node_modules/babel-loader/lib/index.js?!./node_modules/@quasar/app/lib/webpack/loader.auto-import.js?kebab!./node_modules/vue-loader/lib/index.js?!./src/components/Player.vue?vue&type=script&lang=js& (http://localhost:8080/0.js:11:1) at webpack_require (http://localhost:8080/app.js:854:12) at fn (http://localhost:8080/app.js:151:13) at eval code (eval code:2:22) at ./src/components/Player.vue?vue&type=script&lang=js& (http://localhost:8080/0.js:115:1) at webpack_require (http://localhost:8080/app.js:854:12)”}

The only file I have so far where I've added async to it is this one:

```
import Vue from 'vue'
import axios from 'axios'
import convert from 'xml-js'
export default async (/* { app, router, Vue ... } */) => {
  await axios.get('https://www.loatoday.net/feed/mp3')
    .then(function (response) {
      Vue.prototype.$xml = convert.xml2json(response.data, { compact: false, spaces: 1 })
    })
    .catch(function (error) {
      console.log(error)
    })
    .then(function () {
      // always executed
    })
  let xml = JSON.parse(Vue.prototype.$xml)
  let length = xml.elements[0].elements[0].elements.length
  let title = ''
  let description = ''
  let mp3 = ''
  let feed = []

  for (let i = 21; i < length; i++) {
    title = xml.elements[0].elements[0].elements[i].elements[0].elements[0].text
    description = xml.elements[0].elements[0].elements[i].elements[4].elements[0].cdata
    mp3 = xml.elements[0].elements[0].elements[i].elements[6].attributes.url
    feed.push({
      "id": (i - 19),
      "title": title,
      "description": description,
      "mp3": mp3
    })
  }
  Vue.prototype.$image = xml.elements[0].elements[0].elements[4].elements[0].elements[0].text
  Vue.prototype.$title = xml.elements[0].elements[0].elements[4].elements[1].elements[0].text
  Vue.prototype.$url = xml.elements[0].elements[0].elements[4].elements[2].elements[0].text
  Vue.prototype.$description = xml.elements[0].elements[0].elements[2].elements[0].text
  Vue.prototype.$feed = feed
  return feed
}
```

The feed in question is a podcast feed, and my script returns "feed", which is a string. So I don't see what I'm doing wrong.

How can I fix this?

**Comment by study-loading** [comment] 2020-06-09 10:21
`VuePlyr.install = (Vue, options = {}) => {
  if (options.plyr) {
    VuePlyr.props.options.default = () => { return { ...options.plyr } };
  }
  if (options.emit) {
    VuePlyr.props.emit.default = () => { return [...options.emit] };
  }
  Vue.component(VuePlyr.name, VuePlyr);
};

if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(VuePlyr);
}

export default VuePlyr;
`

It appears (surprisingly) that Edge doesn't support property rest yet, you can rewirte install

**Comment by study-loading** [comment] 2020-06-09 11:04
`VuePlyr.install = (Vue, options = {}) => {
  if (options.plyr) {
    VuePlyr.props.options.default = () => {
      return { ...options.plyr }
    }
  }
  if (options.emit) {
    VuePlyr.props.emit.default = () => {
      return [...options.emit]
    }
  }
  Vue.component(VuePlyr.name, VuePlyr)
}`

edge is not support rest

**Comment by redxtech** [comment] 2020-10-31 23:03
I'm pretty sure this is caused by the runtime not being able to parse mjs files. Also, the provided code has nothing to do with vue-plyr as far as I can tell, so I'll close this.

**Closed by redxtech** 2020-10-31 23:03 UTC
