### ISSUE TITLE
vue-plyr module not downloading

### ISSUE THREAD

**Issue by saranyavelpuri** [redxtech/vue-plyr#58] opened 2019-03-01 04:27 UTC
Hi,
vue-plyr was previously working fine, after some update I am unable to download this package using npm , Its always prompting for npm install, even after downloading multiple times.

**Comment by jonathanws** [comment] 2019-03-01 05:13
Could your problem be related to this issue?

#57

**Comment by saranyavelpuri** [comment] 2019-03-01 06:41
yes

**Comment by redxtech** [comment] 2019-03-01 08:56
closing as dupe of #57

**Closed by redxtech** 2019-03-01 08:56 UTC
